# Brick BindingDB
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

stages:
  download:
    cmd: src/1_download.sh 
    deps:
      - src/1_download.sh
    outs:
      - download
  build: 
    cmd: Rscript src/2_build.R
    deps:
      - src/2_build.R
      - download
    outs:
      - brick/bindingdb.parquet