# Brick BindingDB
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

stages:
  download:
    cmd: stages/1_download.sh 
    deps:
      - stages/1_download.sh
    outs:
      - download
  build: 
    cmd: stages/2_build.sh
    deps:
      - stages/2_build.sh
      - stages/bindingDB2parquet.py
      - download
    outs:
      - brick