# Brick BindingDB
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

stages:
  scrape:
    cmd: bash src/0_scrape.sh
    outs: 
      - download/download_link.txt
  download:
    cmd: bash src/1_download.sh
    deps:
      - download/download_link.txt
    outs:
      - download/mysql.tar
  build:
    cmd: Rscript src/2_build_parquet.R
    deps:
      - download/mysql.tar
    outs:
      - brick