# Brick BindingDB
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:
  
  download:
    cmd: bash stages/1_download.sh 
    deps:
      - stages/1_download.sh
    outs:
      - download

  brick:
    cmd: bash stages/2_unzip_build.sh 
    deps: 
      - download
      - stages/2_unzip_build.sh
      - stages/bindingDB2parquet.py
    outs:
      - bindingDB.parquet